package server

// recordRoutes are the records' pages and what is done from them: lists,
// a record, its files, exports, and the pages that gather records (today,
// review, mail to sort, templates, sharing).
var recordRoutes = []route{
	{pattern: "GET /t/{type}", handle: (*Server).listPage, access: people, public: true},
	{pattern: "POST /t/{type}/add", handle: (*Server).addRecord, access: people, tool: "create_record"},
	{pattern: "GET /t/{type}/import", handle: (*Server).importPage, access: owner},
	{pattern: "POST /t/{type}/import", handle: (*Server).importUpload, access: owner, tool: "import_records"},
	{pattern: "POST /t/{type}/import/{file}/run", handle: (*Server).importRun, access: owner, tool: "import_records"},
	{pattern: "GET /t/{type}/{id}", handle: (*Server).detailPage, access: people, public: true},
	{pattern: "GET /t/{type}/{id}/whole", handle: (*Server).wholePage, access: people, public: true},
	{pattern: "POST /t/{type}/{id}/parts/move", handle: (*Server).moveParts, access: people, tool: "organise_writing"},
	{pattern: "POST /t/{type}/{id}/delete", handle: (*Server).deleteForm, access: people, persons: "a record goes when a person deletes it, or when its making is undone"},
	{pattern: "POST /t/{type}/{id}/discard", handle: (*Server).discard, access: people, tool: "undo_change"},
	{pattern: "POST /t/{type}/{id}/props", handle: (*Server).recordProps, access: people, tool: "update_record"},
	{pattern: "POST /t/file/upload", handle: (*Server).upload, access: people, persons: "a file comes from their computer; the assistant reads files already added"},
	// A file and what is read from it are public with the page that shows
	// it; its sound, copied out for writing it down, is not.
	{pattern: "GET /files/{id}", handle: (*Server).serveFile, access: people, public: true},
	{pattern: "GET /files/{id}/still", handle: (*Server).serveStill, access: people, public: true},
	{pattern: "GET /files/{id}/captions.vtt", handle: (*Server).captions, access: people, public: true},
	{pattern: "GET /files/{id}/sound", handle: (*Server).soundPlan, access: people},
	{pattern: "GET /files/{id}/sound/{n}", handle: (*Server).soundChunk, access: people},
	{pattern: "POST /files/{id}/transcribe", handle: (*Server).transcribeFile, access: people, tool: "write_down"},
	{pattern: "GET /files/{id}/transcript.srt", handle: (*Server).transcriptFile, access: people, public: true},
	{pattern: "GET /files/{id}/transcript.txt", handle: (*Server).transcriptFile, access: people, public: true},
	{pattern: "GET /export/workspace.zip", handle: (*Server).exportEverything, access: owner},
	{pattern: "GET /export/all.ics", handle: (*Server).exportCalendar, access: people},
	{pattern: "GET /export/{file}", handle: (*Server).exportFile, access: people, public: true},
	{pattern: "GET /export/{type}/{file}", handle: (*Server).exportDocument, access: people, public: true},
	{pattern: "POST /act/{id}", handle: (*Server).act, access: people, tool: "run_action"},
	{pattern: "POST /suggestions/{id}/{answer}", handle: (*Server).suggestionAnswer, access: people, persons: "a suggestion to their writing is theirs to accept or decline, never the one who suggested it"},
	{pattern: "POST /suggestions/accept-all", handle: (*Server).suggestionsAcceptAll, access: people, persons: "the same, for every fix or formatting change at once"},
	{pattern: "GET /today", handle: (*Server).todayPage, access: people},
	{pattern: "POST /today/done", handle: (*Server).todayDone, access: people, tool: "update_record"},
	{pattern: "POST /today/move", handle: (*Server).todayMove, access: people, tool: "update_record"},
	{pattern: "POST /today/late", handle: (*Server).todayLate, access: people, tool: "update_record"},
	{pattern: "POST /today/sort", handle: (*Server).todaySort, access: people, persons: "it is what they say to the assistant"},
	{pattern: "POST /brief", handle: (*Server).briefSet, access: owner, tool: "set_setting"},
	{pattern: "GET /review", handle: (*Server).reviewPage, access: people},
	{pattern: "POST /review/next", handle: (*Server).reviewMove, access: people, tool: "update_record"},
	{pattern: "POST /review/done", handle: (*Server).reviewDone, access: people, tool: "update_record"},
	{pattern: "POST /review/on", handle: (*Server).reviewOn, access: owner, tool: "set_setting"},
	{pattern: "GET /mail", handle: (*Server).mailPage, access: owner},
	{pattern: "POST /mail/connect", handle: (*Server).mailConnect, access: owner, persons: "a mailbox and its password are its owner's to give"},
	{pattern: "POST /mail/off", handle: (*Server).mailOff, access: owner, persons: "a mailbox and its password are its owner's to give"},
	{pattern: "POST /mail/task", handle: (*Server).mailTask, access: people, tool: "create_record"},
	{pattern: "POST /mail/sorted", handle: (*Server).mailSorted, access: people, tool: "update_record"},
	{pattern: "GET /templates", handle: (*Server).templatesPage, access: people},
	{pattern: "POST /templates/use", handle: (*Server).templateUse, access: people, tool: "add_arrangement"},
	{pattern: "GET /share", handle: (*Server).sharePage, access: people},
	{pattern: "POST /share", handle: (*Server).shareSave, access: people, tool: "create_record"},
}
